backend:
  name: git-gateway
  branch: master

media_folder: "public/news-images"
public_folder: "/news-images"

collections:
  - name: "news"
    label: "Новини"
    folder: "public/news"
    create: true
    extension: "json"
    format: "json"
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Заголовок", name: "title", widget: "string"}
      - {label: "Дата публікації", name: "date", widget: "datetime"}
      - {label: "Опис", name: "description", widget: "text"}
      - {label: "Теги", name: "tags", widget: "list", default: ["#update"]}
      - {label: "Зображення", name: "image", widget: "image", required: false}